### ISSUE TITLE
Aerochat won't appear after login

### ISSUE THREAD

**Issue by LukaTV939** [not-nullptr/Aerochat#1]
when I login, either with token or though the second method, the app doesn't appear
I only get notifications like pings and who's online, nothing else
I was suggested to use event viewer for logs but I don't know how

**Comment by eversiege** [comment]
can replicate issue. Get only notifications and can click over to DMs when they come. Windows 11

**Comment by vys69** [comment]
I have the same issue 🙋‍♂️ I see it was closed, what was the solution?
