### ISSUE TITLE
Downloader is tripping Windows Defender, be a lot cooler if it didint.

### ISSUE THREAD

**Issue by KevinTheGreat333** [not-nullptr/Aerochat#10]
When i tried to download the exe loader, it got lit up by the defender. it also trips SmartScreen when trying to run it. a minor issue but an issue to be resolved nontheless.
![Screenshot_154](https://github.com/user-attachments/assets/54ca17ff-d67a-4620-a2f0-359dbfa999e3)

**Comment by kawapure** [comment]
This is an unavoidable issue.
