### ISSUE TITLE
some scenes shouldnt be scaled

### ISSUE THREAD

**Issue by susususus44** [not-nullptr/Aerochat#13]
here is some examples
![image](https://github.com/user-attachments/assets/dd9bfa0e-3410-4eba-b870-e2f6f6187cdd)
![image](https://github.com/user-attachments/assets/65e88212-745c-4ea0-a633-77dc5866a85f)
![image](https://github.com/user-attachments/assets/9d853047-e4f1-46a4-9b04-d30d9edd4f64)

also i feel like some of the scenes should be looped instead of stretched
![image](https://github.com/user-attachments/assets/c47d3014-de14-4d51-ad9e-2f53a5d65511)

**Comment by not-nullptr** [comment]
i'm replicating wlm 09's behaviour, which is how it acts right now
