### ISSUE TITLE
Multiple instances of the same conversation

### ISSUE THREAD

**Issue by DevJimm** [not-nullptr/Aerochat#16]
When clicking on a contacts name it opens a new window instead of current conversation. It also doesn't remember previous conversation sizing (i think WLM had that)

**Comment by not-nullptr** [comment]
first one is 100% a bug (which i made very sure should not be happening!!)

second one just isn't implemented yet. both r planned :)

**Comment by not-nullptr** [comment]
fixed in 71a0541607be86cd315c9bf137074604acaf4435
