### ISSUE TITLE
Logging in through password doesn't log you in

### ISSUE THREAD

**Issue by highesttt** [not-nullptr/Aerochat#2]
Logging in through the password method, either using the QR code or email+password+2fa doesn't close the discord window and log you in, it just opens discord in web

**Comment by vys69** [comment]
For me it didn't auto log me in, I had to press the log in button again.

**Comment by not-nullptr** [comment]
fixed in https://github.com/not-nullptr/Aerochat/releases/tag/v0.0.0.3
