### ISSUE TITLE
Aero doesn't open after install & login

### ISSUE THREAD

**Issue by vys69** [not-nullptr/Aerochat#4]
### Aero doesn't open after install & login

Once I get it set up & logged in, it doesn't load or run. It displays when some friends come online, but that's about it. I've reinstalled, cleared cache and rebooted pc.

**Comment by vys69** [comment]
### Screenshots
#### Aero chat running in taskmanager
![Aerochat running in task manager](https://github.com/user-attachments/assets/e9092ecb-a4d8-42c6-b1ae-6e595b8ff35d)

**Comment by vys69** [comment]
Compiling from source fixes this.

**Comment by not-nullptr** [comment]
should've been fixed in 0.0.0.2, compiling from source fixing this issue implies that you were running an outdated version. please grab the latest one from https://aerochat.live/download!
