### ISSUE TITLE
Discord's account should disable the textbox in DMs

### ISSUE THREAD

**Issue by dominichayesferen** [not-nullptr/Aerochat#40]
If you've been lucky, or unlucky, enough to receive a Discord DM in your account's lifetime,

The good news is that it actually works fine.

But this bug report is pertaining to the reply function in DMs, notably the inability to actually reply to Discord's DMs.
As you can see, in Discord a Discord DM is uniquely unable to be replied to:

![image](https://github.com/user-attachments/assets/faa10854-ec30-4703-9ac5-6ed9d75d6353)

However, Aerochat did not account for this, hence this bug, and any attempts to reply silently fail:

![image](https://github.com/user-attachments/assets/f4a5ad78-8cf1-4073-9a2e-3e8f60ca818c)

Thus, this bug report exists to suggest that, for Discord DMs, the reply function be disabled just like in read-only channels.

**Comment by dominichayesferen** [comment]
For the record, Discord's UID is 643945264868098049...? huh, was expecting it to be 0 - maybe it's random for each account?

In case it is, their username is just `discord`.

**Comment by not-nullptr** [comment]
i could just hardcode this i guess...

**Comment by not-nullptr** [comment]
side note - discord ids ("snowflakes") aren't random. they're determined based off a few things - an increment, the number of milliseconds since the discord epoch (jan 1st 2015), a worker id and the running process id. this is why you can get the date a snowflake was generated without ever hitting the api
