### ISSUE TITLE
Download now not working.

### ISSUE THREAD

**Issue by PurpleBored** [not-nullptr/Aerochat#51]
So I am running Windows 7 so that could be a big issue but every time i launch Aerochat after installing i get a you must install .Net Desktop Runtime. Sadly after pressing the Download now button nothing happens :( https://0x0.st/Xlq-.png
I tried downloading .Net runtime 8 and 6 but that dosent seem to work.

**Comment by Nlk29** [comment]
I've got the same issue. This seems to be introduced in v0.0.1.1.

**Comment by Nlk29** [comment]
Found a workaround: Install v0.0.1.0 forst and then update to v0.0.1.1

**Comment by PurpleBored** [comment]
Yup it indeed worked for me i guess this needs to be fixed! Big Thanks!

**Comment by kawapure** [comment]
This has been fixed with the latest release. It was because of some .NET-related JSON file being accidentally removed when shipping the installer.
