### ISSUE TITLE
[fixed] Aerochat does not see .NET

### ISSUE THREAD

**Issue by etonedemid** [not-nullptr/Aerochat#52]
I did download .NET SDK and desktop runtime

![image](https://github.com/user-attachments/assets/8dc9c717-d81a-4d9f-827a-d2bd61371c4b)

**Comment by lovelydumpling** [comment]
Encountering the same issue. Reinstalled .NET Desktop Runtime 8 to be certain, still no dice.

**Comment by elaymm4** [comment]
Same

**Comment by lovelydumpling** [comment]
I should mention, installing 0.0.1.0 still works, and then installing 0.0.1.1 over top of it bypasses this problem.

**Comment by JohnCake83** [comment]
encountering the same issue

**Comment by etonedemid** [comment]
Check news on their discord

**Comment by kawapure** [comment]
This has been fixed with the latest release. It was because of some .NET-related JSON file being accidentally removed when shipping the installer.
